import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CallToAction } from '../components/common/CallToAction'
import { ConfirmationNotice } from '../components/common/ConfirmationNotice'
import { PageHero } from '../components/common/PageHero'
import { SectionHeading } from '../components/ui/SectionHeading'
import { industries, companyValues, processSteps, representativeProjects } from '../data/site'
import { useSeo } from '../hooks/useSeo'

export function AboutPage() {
  useSeo({ title: 'About Us', description: 'Learn how Surya Amor Technology approaches document digitization, information management and technology delivery.', path: '/about' })
  return <><PageHero eyebrow="About Surya Amor" title="Technology in service of information that matters." description="We help organizations move from physical and legacy records to useful, controlled digital assets through thoughtful workflows and practical technology." /><section className="section section--white"><div className="container intro-grid"><div className="prose"><h2>Our role</h2><p>Surya Amor Technology Sdn Bhd is positioned as a Malaysian technology and document digitization company supporting the capture, organization, preservation and use of institutional information.</p><p>Our approach begins with the collection and its intended outcome. This keeps the work grounded in handling needs, findability, file integrity, delivery constraints and long-term usefulness.</p><h2>How we create value</h2><p>We connect specialist capture services with OCR, indexing, data conversion, digital archiving, software and information-management capabilities—making it easier to plan an end-to-end programme.</p></div><aside className="intro-panel"><h3>Company facts awaiting approval</h3><p>The site is prepared for a verified company profile without publishing assumptions.</p><ul className="check-list">{['Incorporation and registration details', 'Founding year and leadership profile', 'Official address and service coverage', 'Verified certifications and memberships'].map((item) => <li key={item}><CheckCircle2 size={18} />{item}</li>)}</ul></aside></div></section><section className="section section--tint"><div className="container"><SectionHeading eyebrow="Our working principles" title="The standard behind the workflow." description="These principles guide how the website presents our delivery approach; company leadership should approve them before launch." split /><div className="grid grid--4">{companyValues.map((value) => <article className="card" key={value.title}><h3>{value.title}</h3><p>{value.description}</p></article>)}</div><ConfirmationNotice>Company history, leadership, Malaysian registration information and formal values require confirmation before production publication.</ConfirmationNotice></div></section><CallToAction /></>
}

export function IndustriesPage() {
  useSeo({ title: 'Industries We Serve', description: 'Digitization and information-management approaches for government, archives, libraries, museums, engineering and corporate organizations.', path: '/industries' })
  return <><PageHero eyebrow="Who we serve" title="Different institutions. Different records. One need for usable information." description="We align workflow decisions with the collection, operating environment, stakeholder needs and information risk." /><section className="section"><div className="container"><div className="grid grid--2">{industries.map(({ title, description, icon: Icon }) => <article className="card" key={title}><div className="card__icon"><Icon size={23} aria-hidden="true" /></div><h3 style={{ marginTop: '1.25rem' }}>{title}</h3><p>{description}</p><Link className="card__link" to="/contact">Discuss your environment <ArrowRight size={16} /></Link></article>)}</div></div></section><CallToAction title="Your sector informs the workflow—not a generic package." /></>
}

export function ProjectsPage() {
  useSeo({ title: 'Projects & Portfolio', description: 'A transparent case-study framework for Surya Amor Technology digitization and information-management engagements.', path: '/projects' })
  return <><PageHero eyebrow="Projects & portfolio" title="Evidence should be specific, approved and useful." description="This portfolio area is ready for verified case studies that explain the problem, workflow and result without exposing sensitive records." /><section className="section section--white"><div className="container"><SectionHeading eyebrow="Representative engagement formats" title="Case-study templates awaiting approved projects." description="The examples below illustrate how real engagements can be communicated once the company supplies verified facts and permissions." split /><div className="grid grid--3">{representativeProjects.map((project) => <article className="card" key={project.title}><p className="card__tag">{project.tag}</p><h3>{project.title}</h3><p>{project.description}</p></article>)}</div><ConfirmationNotice>No client, project quantity, duration, result or testimonial is currently claimed. Replace these representative formats with approved material before launch.</ConfirmationNotice></div></section><section className="section section--tint"><div className="container content-layout"><div className="prose"><h2>What a strong case study needs</h2><p>Approved case studies should give prospective clients decision-useful evidence while respecting confidentiality.</p><ul><li>Client sector, named only with permission</li><li>Collection types and approved scale range</li><li>Challenges and constraints</li><li>Delivered workflow and quality approach</li><li>Measured outcomes approved by the client</li></ul></div><aside className="aside-panel"><h2>Content checklist</h2><p>Provide approved copy, redacted images, publication permission and a contact who can verify each claim.</p></aside></div></section><CallToAction /></>
}

export function TechnologyPage() {
  useSeo({ title: 'Technology & Solutions', description: 'Explore capture, OCR, information management, software and infrastructure solution capabilities.', path: '/technology' })
  const areas = [{ title: 'Specialist capture', text: 'Overhead, production, large-format, microform, audiovisual and 3D approaches selected after source assessment.' }, { title: 'Recognition & conversion', text: 'OCR, file transformation, preprocessing and delivery profiles configured around usability goals.' }, { title: 'Information management', text: 'Metadata, classification, records workflows and digital archive structures designed for retrieval and governance.' }, { title: 'Software & integration', text: 'Purpose-built applications and practical integration paths that connect information to the next process.' }, { title: 'Hardware & implementation', text: 'Requirements-led scanner and IT hardware supply with setup, operational readiness and training scope.' }, { title: 'Integrity & preservation', text: 'File profiles, manifests, checksums and lifecycle recommendations that support sustainable stewardship.' }]
  return <><PageHero eyebrow="Technology & solutions" title="The right tool is the one that serves the collection." description="Technology decisions should follow source material, target use, operating constraints and acceptance needs—not brand preference alone." /><section className="section"><div className="container"><div className="grid grid--3">{areas.map((area, index) => <article className="card" key={area.title}><span className="card__tag">Capability 0{index + 1}</span><h3>{area.title}</h3><p>{area.text}</p></article>)}</div><ConfirmationNotice>Specific scanner brands, software products, partner statuses and equipment inventory require company confirmation. None are implied on this page.</ConfirmationNotice></div></section><CallToAction /></>
}

export function ProcessPage() {
  useSeo({ title: 'Our Process', description: 'See the six-stage approach used to plan, capture, quality-assure and hand over digitization projects.', path: '/process' })
  return <><PageHero eyebrow="Our process" title="Defined before production. Visible through delivery." description="A clear workflow reduces surprises by agreeing on material handling, capture, metadata, quality and handover expectations early." /><section className="section section--white"><div className="container"><div className="grid grid--2">{processSteps.map((step) => <article className="card" key={step.number}><span className="card__tag">Stage {step.number}</span><h3>{step.title}</h3><p>{step.description}</p></article>)}</div></div></section><section className="section section--tint"><div className="container"><SectionHeading eyebrow="Control points" title="Decisions that remain visible." description="Each engagement should define these areas in proportion to its risk, scale and intended use." split /><div className="grid grid--4">{['Chain of custody', 'Sample approval', 'Exception handling', 'Quality evidence'].map((item) => <article className="card" key={item}><h3>{item}</h3><p>Requirements and responsibilities are agreed in the project-specific implementation plan.</p></article>)}</div></div></section><CallToAction /></>
}

export function WhyUsPage() {
  useSeo({ title: 'Why Choose Us', description: 'A quality-led, collection-aware approach to digitization, preservation and technology delivery.', path: '/why-us' })
  const reasons = [...companyValues, { title: 'Connected capabilities', description: 'Capture, metadata, conversion, preservation and technology needs can be planned as one workflow.' }, { title: 'Site-flexible planning', description: 'On-site options can be assessed when material movement, access or security constraints require it.' }]
  return <><PageHero eyebrow="Why choose us" title="A better digitization partner asks better questions first." description="Confidence grows from appropriate methods, visible controls and delivery that fits the way information will actually be used." /><section className="section"><div className="container"><div className="grid grid--3">{reasons.map((reason, index) => <article className="card" key={reason.title}><span className="card__tag">0{index + 1}</span><h3>{reason.title}</h3><p>{reason.description}</p></article>)}</div><ConfirmationNotice>Do not add unsupported claims such as “industry-leading”, guaranteed accuracy, years of experience, security certifications or named partnerships without verified evidence.</ConfirmationNotice></div></section><CallToAction /></>
}

export function CareersPage() {
  useSeo({ title: 'Careers', description: 'Explore future career opportunities in digitization, information management and technology at Surya Amor Technology.', path: '/careers' })
  return <><PageHero eyebrow="Careers" title="Build practical technology around information that matters." description="Future opportunities may span digitization operations, quality, metadata, project delivery, software and technical support." /><section className="section section--white"><div className="container content-layout"><div className="prose"><h2>Current openings</h2><p>No verified vacancies have been supplied for publication. This page will list roles only after the company confirms the title, location, employment terms, responsibilities and application channel.</p><h2>Future role areas</h2><ul><li>Digitization operators and quality reviewers</li><li>Metadata and document-indexing specialists</li><li>Project coordination and client delivery</li><li>Software development and systems support</li></ul><h2>Safe applications</h2><p>Do not send identity documents or sensitive personal records through the general website form. A company-approved recruitment email and privacy notice must be supplied before applications are invited.</p></div><aside className="aside-panel"><h2>Vacancy updates</h2><p>There are currently no confirmed roles published.</p><Link className="button button--ghost" to="/contact">General company contact</Link></aside></div></section><CallToAction title="Interested in future opportunities?" description="Check back after the company publishes an approved recruitment channel and vacancy details." /></>
}
